// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmitgM7bgsUJCqZ6DLfxWl1ARSIzq2vtU',
    appId: '1:158779729833:web:b6f538a2e1aaada53f86b8',
    messagingSenderId: '158779729833',
    projectId: 'auralock-73a8d',
    authDomain: 'auralock-73a8d.firebaseapp.com',
    storageBucket: 'auralock-73a8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5L1mmJyhxfZlpzWPLEeOO-wKRv7Gzjx4',
    appId: '1:158779729833:android:7d6625000a86cc4a3f86b8',
    messagingSenderId: '158779729833',
    projectId: 'auralock-73a8d',
    storageBucket: 'auralock-73a8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJnfqsxWXm0l9J1rt5FqF5v1ogjYxT7Q',
    appId: '1:158779729833:ios:eafc8b0cf4e40c793f86b8',
    messagingSenderId: '158779729833',
    projectId: 'auralock-73a8d',
    storageBucket: 'auralock-73a8d.firebasestorage.app',
    iosBundleId: 'com.example.auralock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJnfqsxWXm0l9J1rt5FqF5v1ogjYxT7Q',
    appId: '1:158779729833:ios:eafc8b0cf4e40c793f86b8',
    messagingSenderId: '158779729833',
    projectId: 'auralock-73a8d',
    storageBucket: 'auralock-73a8d.firebasestorage.app',
    iosBundleId: 'com.example.auralock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmitgM7bgsUJCqZ6DLfxWl1ARSIzq2vtU',
    appId: '1:158779729833:web:e6eb79f4f3626c703f86b8',
    messagingSenderId: '158779729833',
    projectId: 'auralock-73a8d',
    authDomain: 'auralock-73a8d.firebaseapp.com',
    storageBucket: 'auralock-73a8d.firebasestorage.app',
  );
}
